import Head from "next/head";
import {
  Navbar,
  Main,
  About,
  Skills,
  Projects,
  Contact,
} from "../components/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Beniamin Antal-Vaida</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  );
}
